#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Fetch the demo data from its sources of truth.

The repo does not store data files. This script pulls each one from where
it was published and verifies it against a checksum:

- ``cs1c02786_si_002.csv`` and ``cs1c02786_si_003.csv`` -- the paper's
  official Figshare deposit (``10.1021/acscatal.1c02786.s002/.s003``).
- ``7OG3.pdb`` -- the RCSB download for PDB 7OG3.
- ``ired88_wt.fasta`` -- written from the published wild-type sequence.
- ``ired88_esmfold.pdb`` -- regenerated by
  ``scripts/predict_structure_esmfold.py`` (the public ESM Fold API returns
  the same coordinates as the original run).

The row-level ``ired-master-table.csv`` and ``layouts.csv`` were never
publicly deposited; the demo notebooks do not read them (only
``data.load_si002`` and ``data.load_si003`` are used), so the script skips
them with a note.

Usage (from the repo root):

    pixi run fetch-data        # or: uv run scripts/fetch_data.py

Pass ``--force`` to re-download files that are already present and valid.
"""

import argparse
import hashlib
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent

# Published wild-type IRED-88 sequence (DMS numbering, no expression tag),
# as deposited in the paper's supporting information.
WT_SEQUENCE = "MTNHASTATTSPAPVTVVGLGPMGLVLAEVLLAKGHPTTVWNRTPERASGLVAQGASLAASITDAVSASPVTIMCLNNYATMYEVFGPAREALRDRVLVNLNSGTPQEVRAAVSWASDLGTRYLDGAIMVPPPLVGRPDAVFLYSGDRAVLDEHRATLASLGDPRFLGADPTLAVLYNTALLHMMYATLNGYLQATALVGSAGVSATEFADIALGWFAPSVLAPSSLAAHAVDLDKGNYPGTLGTLRMNVNALEHIARAAEEQGVHSELPHLMREVAERAVAQGHGDHNYMSVYEAFKQPSPAS"

DOWNLOADS = [
    (
        "data/raw/cs1c02786_si_002.csv",
        "https://ndownloader.figshare.com/files/30878419",
        "6c525ff2a1eea174fd635c9332040625",
        "paper SI-002, Figshare deposit 10.1021/acscatal.1c02786.s002",
        False,
    ),
    (
        "data/raw/cs1c02786_si_003.csv",
        "https://ndownloader.figshare.com/files/30878422",
        "cc48e881412640c3bf80019ac924df40",
        "paper SI-003, Figshare deposit 10.1021/acscatal.1c02786.s003",
        False,
    ),
    (
        "data/external/7OG3.pdb",
        "https://files.rcsb.org/download/7OG3.pdb",
        "d1e45e1761d4c0bde021fa2a2781248b",
        "crystal structure, RCSB PDB 7OG3",
        True,
    ),
]

NOT_PUBLICLY_DEPOSITED = [
    ("data/raw/ired-master-table.csv", "row-level variant records"),
    ("data/raw/layouts.csv", "plate layout metadata"),
]


def md5(path: Path) -> str:
    """Return the MD5 checksum of a file."""
    return hashlib.md5(path.read_bytes()).hexdigest()


def download(url: str, dest: Path, normalize: bool = False) -> None:
    """Download ``url`` to ``dest``, creating parent directories.

    With ``normalize=True`` (for RCSB PDB files), strip trailing whitespace
    from every line. RCSB currently pads PDB-format lines to a fixed width;
    the padding is serialization, not data.
    """
    request = urllib.request.Request(
        url, headers={"User-Agent": "ired-88-research-copilot/1.0"}
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        if normalize:
            text = "\n".join(
                line.rstrip() for line in response.read().decode().splitlines()
            )
            dest.write_text(text + "\n")
        else:
            dest.write_bytes(response.read())


def main() -> int:
    """Fetch every missing data file and verify checksums."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--force",
        action="store_true",
        help="re-download files that are already present and valid",
    )
    args = parser.parse_args()

    failures: list[str] = []

    for rel, url, expected, what, normalize in DOWNLOADS:
        dest = HERE / rel
        if dest.exists() and md5(dest) == expected and not args.force:
            print(f"ok        {rel} (already present)")
            continue
        print(f"fetching  {rel} -- {what}")
        try:
            download(url, dest, normalize=normalize)
        except Exception as exc:  # noqa: BLE001 - report any network failure
            failures.append(rel)
            print(f"  FAILED: {exc}")
            continue
        if md5(dest) != expected:
            failures.append(rel)
            print(f"  FAILED: checksum mismatch (expected md5 {expected})")
        else:
            print("  ok (md5 verified)")

    fasta = HERE / "data" / "external" / "ired88_wt.fasta"
    fasta_text = f">IRED-88_WT\n{WT_SEQUENCE}\n"
    if fasta.exists() and fasta.read_text() == fasta_text and not args.force:
        print(f"ok        {fasta.relative_to(HERE)} (already present)")
    else:
        fasta.parent.mkdir(parents=True, exist_ok=True)
        fasta.write_text(fasta_text)
        print(f"wrote     {fasta.relative_to(HERE)} (published wild-type sequence)")

    esmfold = HERE / "data" / "external" / "ired88_esmfold.pdb"
    if esmfold.exists() and not args.force:
        print(f"ok        {esmfold.relative_to(HERE)} (already present)")
    else:
        print("fetching  data/external/ired88_esmfold.pdb -- ESM Fold API prediction")
        result = subprocess.run(
            [sys.executable, HERE / "scripts" / "predict_structure_esmfold.py"],
            check=False,
        )
        if result.returncode != 0 or not esmfold.exists():
            failures.append(str(esmfold.relative_to(HERE)))
            print("  FAILED: prediction did not produce the file")

    for rel, what in NOT_PUBLICLY_DEPOSITED:
        dest = HERE / rel
        state = "present" if dest.exists() else "absent"
        print(
            f"skipping  {rel} ({what}) -- never publicly deposited; {state}. "
            "The demo notebooks do not read it."
        )

    if failures:
        print(f"\n{len(failures)} file(s) failed: {', '.join(failures)}")
        return 1
    print("\nAll data verified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
